apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: frontend
labels:
  template: frontend
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      app: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          app: ${APPLICATION_NAME}
      spec:
        containers:
          -
            name: ${APPLICATION_NAME}
            image: ""
            imagePullPolicy: Always
            env:
              - name: labno
                value: ${LABNO}
              - name: studno
                value: ${STUDENTNO}
              - name: url
                value: ${URL}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:v1
parameters:
  - name: APPLICATION_NAME
    description: "The name of the Image stream (input)."
    required: false
    value: "frontend"
  - name: APP_NAMESPACE
    description: "The namespace of the application."
    required: true
  - description: URL
    displayName: URL
    name: URL
    value: https://127.0.0.1:3001
  - description: LABNO
    displayName: LABNO
    name: LABNO
    value: "1192"
  - description: Student Number
    displayName: Student Number
    name: STUDENTNO
    value: "1"
